name: Periodic Health Check

on:
  schedule:
    - cron: '0 17,18,19,20,21,22,23 * * *'

jobs:
  periodic_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed app health
        uses: jtalk/url-health-check-action@9f9a163f533fcbf8b3d9fe1bf5458e8c23502698
        with:
          url: https://fso21-p11.herokuapp.com/api/health
