name: ex_20_21

on:
  push:
    branches:
      - ejected

jobs:
  ex_20_21:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        mongodb-version: ['4.4']
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: npm install 
        run: npm install

      - name: lint
        run: npm run eslint
      
      - name: Test api endpoints and frontend components
        env:
          TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
          SECRET: ${{ secrets.SECRET }}
        run: npm run test
